
        // ============ FIGHTER DATA ============
        const FIGHTERS_RAW = [
            ["F001","Ammo Williams","Middles","",0,"USA"],
            ["F002","Carlos Adames","Middles","WBC",1,"Dominican Republic"],
            ["F003","Lester Martínez","Middles","",0,"Guatemala"],
            ["F004","Teremoana Teremoana","Heavies","",0,"Australia"],
            ["F005","Keith Thurman","Welters","",0,"USA"],
            ["F006","Moses Itauma","Heavies","",0,"United Kingdom"],
            ["F007","Sebastian Fundora","Welters","WBC",1,"USA"],
            ["F008","Yoenli Hernandez","Middles","",0,"Cuba"],
            ["F009","Willy Hutchinson","Middles","",0,"United Kingdom"],
            ["F010","Deontay Wilder","Heavies","",0,"USA"],
            ["F011","Derek Chisora","Heavies","",0,"United Kingdom"],
            ["F012","Lauren Price","Welters","IBF, WBA, WBC",3,"United Kingdom"],
            ["F013","Paulo Aokuso","Middles","",0,"Australia"],
            ["F014","Sam Goodman","Smalls","",0,"Australia"],
            ["F015","Tim Tszyu","Welters","",0,"Australia"],
            ["F016","Caroline Dubois","Lights","WBC",1,"United Kingdom"],
            ["F017","Ellie Scotney","Smalls","WBO, IBF, WBC",3,"United Kingdom"],
            ["F018","Juan Francisco Estrada","Smalls","",0,"Mexico"],
            ["F019","Osleys Iglesias","Middles","",0,"Cuba"],
            ["F020","Tenshin Nasukawa","Smalls","",0,"Japan"],
            ["F021","Arslanbek Makhmudov","Heavies","",0,"Canada"],
            ["F022","Conor Benn","Welters","",0,"United Kingdom"],
            ["F023","Justis Huni","Heavies","",0,"Australia"],
            ["F024","Richard Riakporhe","Heavies","",0,"United Kingdom"],
            ["F025","Tyson Fury","Heavies","",0,"United Kingdom"],
            ["F026","Alycia Baumgardner","Lights","WBO, IBF, WBA",3,"USA"],
            ["F027","Callum Smith","Middles","",0,"United Kingdom"],
            ["F028","David Morrell","Middles","",0,"Cuba"],
            ["F029","Luis Nery","Smalls","",0,"Mexico"],
            ["F030","Jason Moloney","Smalls","",0,"Australia"],
            ["F031","Conor Wallace","Middles","",0,"Australia"],
            ["F032","Bakary Samake","Welters","",0,"France"],
            ["F033","Lawrence Okolie","Heavies","",0,"United Kingdom"],
            ["F034","Tony Yoka","Heavies","",0,"France"],
            ["F035","Skye Nicholson","Smalls","",0,"Australia"],
            ["F036","Junto Nakatani","Smalls","IBF, WBC",2,"Japan"],
            ["F037","Naoya Inoue","Smalls","WBO, IBF, WBA, WBC",4,"Japan"],
            ["F038","Takuma Inoue","Smalls","",0,"Japan"],
            ["F039","Yoshiki Takei","Smalls","",0,"Japan"],
            ["F040","David Benavidez","Heavies","",0,"Mexico"],
            ["F041","Gilberto Ramirez","Heavies","WBA, WBO",2,"Mexico"],
            ["F042","Daniel Dubois","Heavies","",0,"United Kingdom"],
            ["F043","Fabio Wardley","Heavies","WBO",1,"United Kingdom"],
            ["F044","Adam Azim","Lights","",0,"United Kingdom"],
            ["F045","Dmitry Bivol","Middles","WBA, IBF, WBO",3,"Russia"],
            ["F046","Oleksandr Usyk","Heavies","WBA, WBC, IBF",3,"Ukraine"],
            ["F047","Jack Catterall","Welters","",0,"United Kingdom"],
            ["F048","Errol Spence","Welters","",0,"USA"],
            ["F049","Emanuel Navarrete","Lights","WBO",1,"Mexico"],
            ["F050","Brandon Figueroa","Smalls","",0,"USA"],
            ["F051","Dalton Smith","Lights","WBC",1,"United Kingdom"],
            ["F052","Ryan Garcia","Lights","",0,"USA"],
            ["F053","Shakur Stevenson","Lights","WBC",1,"USA"],
            ["F054","Xander Zayas","Welters","WBO",1,"Puerto Rico"],
            ["F055","Anthony Cacace","Lights","",0,"United Kingdom"],
            ["F056","Raymond Muratalla","Lights","IBF",1,"USA"],
            ["F057","Gabriela Fundora","Smalls","WBO, IBF, WBA, WBC",4,"USA"],
            ["F058","Claressa Shields","Heavies","WBA, WBC, WBO, IBF",4,"USA"],
            ["F059","Gary Antuanne Russell","Lights","WBA",1,"USA"],
            ["F060","Anthony Olascuaga","Smalls","",0,"USA"],
            ["F061","Amanda Serrano","Smalls","WBO, WBA",2,"Puerto Rico"],
            ["F062","Bruce Carrington","Smalls","",0,"USA"],
            ["F063","Keyshawn Davis","Lights","",0,"USA"],
            ["F064","Oscar Collazo","Smalls","WBO, WBA",2,"Puerto Rico"],
            ["F065","Agit Kabayel","Heavies","",0,"Germany"],
            ["F066","Christian Medina","Smalls","WBO",1,"Mexico"],
            ["F067","Emiliano Vargas","Lights","",0,"USA"],
            ["F068","Jadier Herrera","Lights","",0,"Cuba"],
            ["F069","Jai Opetaia","Heavies","IBF",1,"Australia"],
            ["F070","Ryosuke Nishida","Smalls","",0,"Japan"],
            ["F071","Arnold Barboza Jr","Lights","",0,"USA"],
            ["F072","Abass Baraou","Welters","WBA",1,"Germany"],
            ["F073","Bektemir Melikuziev","Middles","",0,"Uzbekistan"],
            ["F074","Callum Walsh","Welters","",0,"Ireland"],
            ["F075","Eduardo Nunez","Lights","IBF",1,"Mexico"],
            ["F076","Efe Ajagba","Heavies","",0,"Nigeria"],
            ["F077","Jarrell Miller","Heavies","",0,"USA"],
            ["F078","Leigh Wood","Smalls","",0,"United Kingdom"],
            ["F079","Liam Wilson","Lights","",0,"Australia"],
            ["F080","Mario Barrios","Welters","WBC",1,"USA"],
            ["F081","Najee Lopez","Middles","",0,"USA"],
            ["F082","Serhii Bohachuk","Welters","",0,"Ukraine"],
            ["F083","Teofimo Lopez","Lights","WBO",1,"USA"],
            ["F084","Alexis Rocha","Welters","",0,"USA"],
            ["F085","Jazza Dickens","Lights","WBA",1,"United Kingdom"],
            ["F086","Andy Cruz","Lights","",0,"Cuba"],
            ["F087","Bakhram Murtazaliev","Welters","IBF",1,"Russia"],
            ["F088","Israil Madrimov","Welters","",0,"Uzbekistan"],
            ["F089","Nick Ball","Smalls","WBA",1,"United Kingdom"],
            ["F090","Raul Curiel","Welters","",0,"Mexico"],
            ["F091","Subriel Matias","Lights","",0,"Puerto Rico"],
            ["F092","David Allen","Heavies","",0,"United Kingdom"],
            ["F093","Frank Martin","Lights","",0,"USA"],
            ["F094","Michael Zerafa","Middles","",0,"Australia"],
            ["F095","Nikita Tszyu","Welters","",0,"Australia"],
            ["F096","Oleksandr Gvozdyk","Middles","",0,"Ukraine"],
            ["F097","Aaron McKenna","Middles","",0,"Russia"],
            ["F098","Abdullah Mason","Lights","WBO",1,"USA"],
            ["F099","Alan Picasso","Smalls","",0,"Mexico"],
            ["F100","Albert Ramirez","Middles","",0,"Venezuela"],
            ["F101","Andrew Moloney","Smalls","",0,"Australia"],
            ["F102","Andy Ruiz","Heavies","",0,"Mexico"],
            ["F103","Angelo Leo","Smalls","IBF",1,"USA"],
            ["F104","Anthony Joshua","Heavies","",0,"United Kingdom"],
            ["F105","Anthony Yarde","Middles","",0,"United Kingdom"],
            ["F106","Armando Resendiz","Middles","",0,"Mexico"],
            ["F107","Artur Beterbiev","Middles","",0,"Canada"],
            ["F108","Bakhodir Jalolov","Heavies","",0,"Uzbekistan"],
            ["F109","Ben Whittaker","Middles","",0,"United Kingdom"],
            ["F110","Brian Norman Jr","Welters","",0,"USA"],
            ["F111","Caleb Plant","Middles","",0,"USA"],
            ["F112","Canelo Alvarez","Middles","",0,"Mexico"],
            ["F113","Charles Conwell","Welters","",0,"USA"],
            ["F114","Chocolatito","Smalls","",0,"Nicaragua"],
            ["F115","Chris Eubank Jr","Middles","",0,"United Kingdom"],
            ["F116","Christian Mbilli","Middles","",0,"France"],
            ["F117","Conah Walker","Welters","",0,"United Kingdom"],
            ["F118","David Nyika","Heavies","",0,"New Zealand"],
            ["F119","Delante Johnson","Lights","",0,"USA"],
            ["F120","Devin Haney","Welters","WBO",1,"USA"],
            ["F121","Diego Pacheco","Middles","",0,"USA"],
            ["F122","Edgar Berlanga","Middles","",0,"Puerto Rico"],
            ["F123","Erickson Lubin","Welters","",0,"USA"],
            ["F124","Erislandy Lara","Middles","WBA",1,"Cuba"],
            ["F125","Ernesto Mercado","Lights","",0,"USA"],
            ["F126","Filip Hrgovic","Heavies","",0,"Croatia"],
            ["F127","Floyd Schofield","Lights","",0,"USA"],
            ["F128","Frank Sanchez","Heavies","",0,"Cuba"],
            ["F129","Galal Yafai","Smalls","",0,"United Kingdom"],
            ["F130","Gervonta Davis","Lights","WBA",1,"USA"],
            ["F131","Guido Vianello","Heavies","",0,"Italy"],
            ["F132","Hamzah Sheeraz","Middles","",0,"United Kingdom"],
            ["F133","Isaac Cruz","Lights","",0,"Mexico"],
            ["F134","Jaime Munguia","Middles","",0,"Mexico"],
            ["F135","Jared Anderson","Heavies","",0,"USA"],
            ["F136","Jaron Ennis","Welters","",0,"USA"],
            ["F137","Jermall Charlo","Middles","",0,"USA"],
            ["F138","Jermell Charlo","Welters","",0,"USA"],
            ["F139","Jesse Rodriguez","Smalls","WBO, WBA, WBC",3,"USA"],
            ["F140","Jesus Alejandro Ramos","Welters","",0,"Mexico"],
            ["F141","Jorge Garcia Perez","Welters","",0,"Mexico"],
            ["F142","Joseph Parker","Heavies","",0,"New Zealand"],
            ["F143","Joshua Buatsi","Middles","",0,"United Kingdom"],
            ["F144","Katie Taylor","Lights","WBO, IBF, WBA",3,"Ireland"],
            ["F145","Kenshiro Teraji","Smalls","",0,"Japan"],
            ["F146","Lamont Roach","Lights","",0,"USA"],
            ["F147","Lenier Pero","Heavies","",0,"Cuba"],
            ["F148","Lewis Crocker","Welters","IBF",1,"United Kingdom"],
            ["F149","Liam Paro","Lights","",0,"Australia"],
            ["F150","Liam Smith","Welters","",0,"United Kingdom"],
            ["F151","Luis Alberto Lopez","Lights","",0,"Mexico"],
            ["F152","Lyndon Arthur","Middles","",0,"United Kingdom"],
            ["F153","Manny Pacquiao","Welters","",0,"Philippines"],
            ["F154","Martin Bakole","Heavies","",0,"Congo"],
            ["F155","Mikaela Mayer","Welters","WBO, WBA, WBC",3,"USA"],
            ["F156","Murat Gassiev","Heavies","",0,"Russia"],
            ["F157","Murodjon Akhmadaliev","Smalls","",0,"Uzbekistan"],
            ["F158","O'Shaquie Foster","Lights","WBC",1,"USA"],
            ["F159","Oscar Valdez","Lights","",0,"Mexico"],
            ["F160","Otto Wallin","Heavies","",0,"Sweden"],
            ["F161","Paddy Donovan","Welters","",0,"Ireland"],
            ["F162","Rafael Espinoza","Smalls","WBO",1,"Mexico"],
            ["F163","Raymond Ford","Lights","",0,"USA"],
            ["F164","Ricardo Rafael Sandoval","Smalls","WBA, WBC",2,"USA"],
            ["F165","Richard Torrez Jr","Heavies","",0,"USA"],
            ["F166","Richardson Hitchins","Lights","IBF",1,"USA"],
            ["F167","Robeisy Ramirez","Smalls","",0,"Cuba"],
            ["F168","Rohan Polanco","Welters","",0,"Dominican Republic"],
            ["F169","Rolando Romero","Welters","WBC",1,"USA"],
            ["F170","Sebastian Reyes","Smalls","",0,"Mexico"],
            ["F171","Seiya Tsutsumi","Smalls","",0,"Japan"],
            ["F172","Shakhram Giyasov","Welters","",0,"Uzbekistan"],
            ["F173","Srisaket Sor Rungvisai","Smalls","",0,"Thailand"],
            ["F174","Stephen Fulton","Smalls","",0,"USA"],
            ["F175","Terence Crawford","Middles","",0,"USA"],
            ["F176","Troy Isley","Middles","",0,"USA"],
            ["F177","Vergil Ortiz Jr","Welters","",0,"USA"],
            ["F178","William Zepeda","Lights","",0,"Mexico"],
            ["F179","Zhanibek Alimkhanuly","Middles","IBF, WBO",2,"Kazakhstan"],
            ["F180","Zhilei Zhang","Heavies","",0,"China"],
        ];

        const COUNTRY_FLAGS = {
            'USA':'🇺🇸','United Kingdom':'🇬🇧','Australia':'🇦🇺','Canada':'🇨🇦','Mexico':'🇲🇽','Cuba':'🇨🇺','Japan':'🇯🇵',
            'Russia':'🇷🇺','Ukraine':'🇺🇦','France':'🇫🇷','Germany':'🇩🇪','Puerto Rico':'🇵🇷','Dominican Republic':'🇩🇴',
            'Guatemala':'🇬🇹','Ireland':'🇮🇪','Uzbekistan':'🇺🇿','Kazakhstan':'🇰🇿','New Zealand':'🇳🇿','Italy':'🇮🇹',
            'Croatia':'🇭🇷','Sweden':'🇸🇪','Philippines':'🇵🇭','Congo':'🇨🇩','Nigeria':'🇳🇬','Thailand':'🇹🇭','Venezuela':'🇻🇪','Nicaragua':'🇳🇮','China':'🇨🇳'
        };

        const UPCOMING_FIGHTS = [
            { date:'2026-03-28', fighterA:'Sebastian Fundora', fighterB:'Keith Thurman', belt:'WBC Super Welterweight', venue:'Las Vegas', network:'Prime Video PPV', flagA:'🇺🇸', flagB:'🇺🇸' },
            { date:'2026-03-28', fighterA:'Carlos Adames', fighterB:'Ammo Williams', belt:'WBC Middleweight', venue:'Manchester, UK', network:'DAZN', flagA:'🇩🇴', flagB:'🇺🇸' },
            { date:'2026-03-28', fighterA:'Moses Itauma', fighterB:'Jermaine Franklin', belt:'Heavyweight', venue:'Manchester, UK', network:'DAZN', flagA:'🇬🇧', flagB:'🇺🇸' },
            { date:'2026-04-04', fighterA:'Deontay Wilder', fighterB:'Derek Chisora', belt:'Heavyweight', venue:'O2 Arena, London', network:'DAZN', flagA:'🇺🇸', flagB:'🇬🇧' },
            { date:'2026-04-05', fighterA:'Caroline Dubois', fighterB:'Terri Harper', belt:'World Title Unification', venue:'London', network:'Sky Sports', flagA:'🇬🇧', flagB:'🇬🇧' },
            { date:'2026-04-05', fighterA:'Ellie Scotney', fighterB:'Mayelli Flores', belt:'Undisputed Super Bantamweight', venue:'London', network:'Sky Sports', flagA:'🇬🇧', flagB:'🇲🇽' },
            { date:'2026-04-11', fighterA:'Tyson Fury', fighterB:'Arslanbek Makhmudov', belt:'Heavyweight', venue:'Tottenham Hotspur Stadium', network:'Netflix', flagA:'🇬🇧', flagB:'🇨🇦' },
            { date:'2026-04-11', fighterA:'Conor Benn', fighterB:'Regis Prograis', belt:'Welterweight', venue:'Tottenham Hotspur Stadium', network:'Netflix', flagA:'🇬🇧', flagB:'🇺🇸' },
            { date:'2026-04-11', fighterA:'Justis Huni', fighterB:'Frazer Clarke', belt:'Heavyweight', venue:'Tottenham Hotspur Stadium', network:'Netflix', flagA:'🇦🇺', flagB:'🇬🇧' },
            { date:'2026-04-17', fighterA:'Alycia Baumgardner', fighterB:'Bo Mi Re Shin', belt:'IBF, WBO, WBA Jr. Lightweight', venue:'New York', network:'ESPN', flagA:'🇺🇸', flagB:'🇰🇷' },
            { date:'2026-05-02', fighterA:'Naoya Inoue', fighterB:'Junto Nakatani', belt:'Undisputed Jr. Featherweight', venue:'Tokyo', network:'ESPN+', flagA:'🇯🇵', flagB:'🇯🇵' },
            { date:'2026-05-02', fighterA:'Gilberto Ramirez', fighterB:'David Benavidez', belt:'WBO & WBA Cruiserweight', venue:'Las Vegas', network:'DAZN', flagA:'🇲🇽', flagB:'🇲🇽' },
            { date:'2026-05-09', fighterA:'Fabio Wardley', fighterB:'Daniel Dubois', belt:'WBO Heavyweight', venue:'Manchester', network:'DAZN', flagA:'🇬🇧', flagB:'🇬🇧' },
            { date:'2026-05-23', fighterA:'Oleksandr Usyk', fighterB:'Rico Verhoeven', belt:'WBC Heavyweight', venue:'Giza, Egypt', network:'DAZN', flagA:'🇺🇦', flagB:'🇳🇱' },
            { date:'2026-09-19', fighterA:'Floyd Mayweather', fighterB:'Manny Pacquiao', belt:'Exhibition / Special Event', venue:'The Sphere, Las Vegas', network:'Netflix', flagA:'🇺🇸', flagB:'🇵🇭' },
        ];

        const TEAM_COLORS = ['#e63333', '#f0c030', '#3388dd', '#40b870', '#e87830', '#888888', '#a06830', '#8860c0', '#e060a0'];
        const DIVISIONS = ['Heavies', 'Middles', 'Welters', 'Lights', 'Smalls'];

        // Convert raw fighter data to objects
        let fighters = FIGHTERS_RAW.map(f => ({
            id: f[0],
            name: f[1],
            division: f[2],
            belts: f[3],
            beltCount: f[4],
            country: f[5],
            flag: COUNTRY_FLAGS[f[5]] || '🏳️'
        }));

        // Create teams
        let teams = [
            { id: 'team_0', name: 'Team Alpha', color: TEAM_COLORS[0] },
            { id: 'team_1', name: 'Team Beta', color: TEAM_COLORS[1] },
            { id: 'team_2', name: 'Team Gamma', color: TEAM_COLORS[2] },
            { id: 'team_3', name: 'Team Delta', color: TEAM_COLORS[3] },
        ];
